#!/usr/bin/perl
use Biblio::Isis;
use Data::Dumper;

my $isis = new Biblio::Isis( isisdb => '../repert/data/', );

for ( my $mfn = 1 ; $mfn <= $isis->count ; $mfn++ ) {
    print Dumper($isis->to_hash($mfn)), "\n";
}
