PROGRAM CHKPWD(S:STRING)  [MENU];

VAR DBNAME: STRING;

FUNCTION CHECK: STRING;

VAR CNT: REAL;
    PW: STRING;
    
BEGIN
  CLEAR;
  CURSOR(10,10); WRITE('ENTER PASSWORD ');
  CNT:=0;
  REPEAT
    ATTR(' ',5,10,25,6); READLN(PW);
    CNT:=CNT+1;  { COUNT NUMBER OF TRIALS }
    IF PW<>'X12Y' THEN
    BEGIN
      CURSOR(12,25);
      WRITELN(CHR(7),'INVALID PASSWORD');
    END;
  UNTIL (PW='X12Y') OR (CNT>2); { ALLOW 2 TRIALS AT MOST }
  IF PW<>'X12Y'
    THEN CHECK:=' ' ELSE CHECK:='.E';
END;

BEGIN
  IF DBNAME='' THEN   { NONE CURRENTLY SELECTED DATA BASE }
  BEGIN
    CLEARMSG; WRITE('DATA BASE NAME? '); READLN(DBNAME);
    IF DBNAME<>'' THEN OPEN(DBNAME);
  END;
  IF DBN='' THEN S:=' '  { IF NO DATA BASE SELECTED REDISPLAY MENU }
            ELSE IF DBN='CDS'
              THEN S:=CHECK  { IF CDS DATA BASE SELECTED THEN CHECK PASSWORD }
              ELSE S:='.E';  { OK FOR ALL OTHER DATA BASES }
END.              
